name = "barnacle"
version = "2.0.0"

description = "Self-healing clusters for Gleam applications on the BEAM!"
licences = ["MIT"]
repository = { type = "github", user = "Pevensie", repo = "barnacle" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.27.0 and < 1.0.0"
gleam_otp = ">= 0.12.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
